name: Repo Audit

on:
  push:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run audit
        run: |
          python -V
          mkdir -p reports scripts
          if [ ! -f scripts/audit_repo.py ]; then
            echo "ERROR: scripts/audit_repo.py not found"; exit 1
          fi
          python scripts/audit_repo.py

      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit
          path: reports/*
          if-no-files-found: error
